spring.application.name=Firebase Excel Manager

# Puerto de la aplicación
server.port=8080

# Tamaño máximo de archivo para carga (ajusta según necesidad)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Ruta al archivo de credenciales Firebase (dentro de resources/)
firebase.credentials.path=firebase/serviceAccountKey.json

# Thymeleaf
spring.thymeleaf.cache=false
